spring:
   application:
      name:　homepage
      
   servlet:
      multipart:
         max-file-size: 5MB
         max-request-size: 6MB
   
   datasource:
      url: ${DB_URL:jdbc:postgresql://localhost:5432/homepage}
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
      
cors:
   allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  
file:
   upload-dir: ${UPLOAD_DIR:./uploads}